### ISSUE TITLE
Reference error

### ISSUE THREAD

**Issue by mmalecki** [rjrodger/seneca-web#4]
I think this happens when `pin: 'role:loadbalance,cmd:*'` is passed to `seneca-web`.

```
ReferenceError: seneca is not defined
    at /home/maciej/dev/js/seneca-web/web.js:328:15
    at wrapcb (/home/maciej/dev/js/seneca-web/node_modules/parambulator/parambulator.js:841:18)
    at /home/maciej/dev/js/seneca-web/node_modules/parambulator/parambulator.js:950:13
    at /home/maciej/dev/js/seneca-web/node_modules/parambulator/parambulator.js:869:24
    at Object.fail (/home/maciej/dev/js/seneca-web/node_modules/parambulator/parambulator.js:596:12)
    at Object.func (/home/maciej/dev/js/seneca-web/node_modules/parambulator/parambulator.js:97:28)
    at execrule (/home/maciej/dev/js/seneca-web/node_modules/parambulator/parambulator.js:866:18)
    at /home/maciej/dev/js/seneca-web/node_modules/parambulator/parambulator.js:873:17
    at Object.func (/home/maciej/dev/js/seneca-web/node_modules/parambulator/parambulator.js:108:7)
    at execrule (/home/maciej/dev/js/seneca-web/node_modules/parambulator/parambulator.js:866:18)
```

**Comment by rjrodger** [comment]
obsolete - offending code removed
